[package]
name = "rust-httplistener"
version = "0.1.0"
authors = ["Sarik Siddiqui <siddiquisarik@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
